services:
  - type: worker
    name: linksharebot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: PORT
        value: 8080
